services:
  # Frontend
  react:
    container_name: react
    build: twitter-demo
    ports:
      - 5173
    develop:
      watch:
        - action: sync
          path: twitter-demo
          target: /usr/src/app
